language: node_js
node_js:
  - "12.8.0"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g ionic
  - npm install -g @angular/cli
script:
  -ionic build --prod  
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}