language: node_js
node_js:
  - "12.8.0"
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
sccriot:
  - echo "deploying"
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
