language: node_js
node_js:
  - "12.8.0"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g ionic
script:
  -ng add @angular/pwa
  -ionic build --prod --service-worker
  -ionic build --prod
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
