language: node_js
node_js:
  - "12.8.0"
      
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g ionic cordova@5.0.0
  - npm install -g ionic@5.0.0

script:
  - ng add @angular/pwa
  - ionic build --service-worker
  
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
