language: node_js
node_js:
  - "12.8.0"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable  
      
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install -g ionic cordova

script:
  - ng add @angular/pwa
  - ionic build --prod --service-worker
  - ionic build --prod
  
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
